
# Use root/example user/password credentials
version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src/:/var/www/html/

  db:
    
    image: mysql
    # Remove the platform line if not running on ARM (m1) macbook. When we host, this will be removed. 
    #image: arm64v8/mysql:oracle 
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
      - ./certs/certificate.pem:/etc/ssl/certs/certificate.pem
      - ./certs/privatekey.pem:/etc/ssl/private/privatekey.pem
    ports:
      - 3036:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql-data: